version: 2
jobs:
  spellcheck:
    docker:
      - image: ryanbw/spellcheck:aspell-latest
    steps:
      - checkout
      - run:
          name: Spellcheck
          command: |
            shopt -s nullglob
            echo "Spellcheck results:"
            for file in {,**/}*.{tex,org}; do
              spellcheck_result="$(aspell -d en_US -p ./local-dictionary -t --add-tex-command 'autocite OOp' list < $file | uniq | sed s_^_${file}:\ _)"
              spellcheck_results="$spellcheck_results$spellcheck_result"
              echo "$spellcheck_result"
            done
            [ "$spellcheck_results" = "" ]
workflows:
  version: 2
  workflow:
    jobs:
      - spellcheck
